name: Deployment Pipeline
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      # - name: Build the project
      #   run: npm run build

      # - name: Create Sentry release
      #   uses: getsentry/action-release@v1
      #   env:
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #     SENTRY_ORG: ${{ secrets.SENTRY_ORG}}
      #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT}}
      #   with:
      #     environment: production
      #     sourcemaps: ./dist
      #     version: ${{ github.sha }}

      # - name: Run tests
      #   run: npm run test

      - name: Trigger deployment
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK}}"
